# Generated by Django 5.0.4 on 2024-05-20 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cumtafapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
